// Generated by Wrangler by running `wrangler types`

interface Env {
  // OAuth Configuration
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  HOSTED_DOMAIN?: string;
  COOKIE_ENCRYPTION_KEY?: string;

  // Stripe Configuration
  STRIPE_PUBLISHABLE_KEY?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  STRIPE_ONE_TIME_PRICE_ID?: string;
  STRIPE_SUBSCRIPTION_PRICE_ID?: string;
  STRIPE_METERED_PRICE_ID?: string;

  // Base URL
  BASE_URL?: string;

  // Email Service Configuration
  EMAIL_SERVICE?: string;

  // SMTP Configuration
  SMTP_HOST?: string;
  SMTP_PORT?: string;
  SMTP_SECURE?: string;
  SMTP_USER?: string;
  SMTP_PASS?: string;
  SMTP_SERVICE?: string;
  SMTP_POOL?: string;
  SMTP_MAX_CONNECTIONS?: string;
  SMTP_MAX_MESSAGES?: string;

  // Gmail Configuration
  GMAIL_USER?: string;
  GMAIL_PASS?: string;

  // AWS SES Configuration
  AWS_ACCESS_KEY_ID?: string;
  AWS_SECRET_ACCESS_KEY?: string;
  AWS_REGION?: string;

  // Default Email Settings
  DEFAULT_SENDER_EMAIL?: string;
  DEFAULT_REPLY_TO_EMAILS?: string;
  DEBUG_EMAIL?: string;

  // Bindings
  OAUTH_KV: KVNamespace;
  EMAIL_TEMPLATES_KV: KVNamespace;
  MCP_OBJECT: DurableObjectNamespace;
} 